# Generated by Django 6.0.3 on 2026-03-26 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_number', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('breed', models.CharField(choices=[('friesian', 'Friesian'), ('ayrshire', 'Ayrshire'), ('jersey', 'Jersey'), ('guernsey', 'Guernsey'), ('sahiwal', 'Sahiwal'), ('crossbreed', 'Crossbreed'), ('other', 'Other')], max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_lactating', models.BooleanField(default=False)),
                ('needs_attention', models.BooleanField(default=False)),
                ('tracking_stage', models.CharField(choices=[('registered', 'Registered'), ('pregnant', 'Pregnant'), ('nearing_calving', 'Nearing calving'), ('active_labor', 'Active labor'), ('post_calving', 'Post-calving')], default='registered', max_length=32)),
                ('photo', models.FileField(blank=True, upload_to='cow_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'cow_number'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'cow_number'), name='unique_cow_number_per_owner')],
            },
        ),
    ]
