# Generated by Django 6.0.3 on 2026-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='insemination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='insemination_type',
            field=models.CharField(blank=True, choices=[('artificial_insemination', 'Artificial insemination'), ('natural_service', 'Natural service')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cow',
            name='last_heat_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='pregnancy_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='reproductive_status',
            field=models.CharField(blank=True, choices=[('not_inseminated', 'Not inseminated yet'), ('inseminated', 'Already inseminated'), ('pregnancy_confirmed', 'Pregnancy confirmed'), ('near_calving', 'Near calving')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='cow',
            name='tracking_stage',
            field=models.CharField(choices=[('registered', 'Registered'), ('inseminated', 'Inseminated'), ('pregnant', 'Pregnant'), ('nearing_calving', 'Nearing calving'), ('active_labor', 'Active labor'), ('post_calving', 'Post-calving')], default='registered', max_length=32),
        ),
    ]
