# Generated by Django 6.0.3 on 2026-03-26 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_dashboard', '0003_inseminationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('heat_observed', 'Heat observed'), ('insemination_recorded', 'Insemination recorded'), ('pregnancy_confirmed', 'Pregnancy confirmed'), ('pregnancy_not_kept', 'Pregnancy not kept'), ('calved', 'Calved')], max_length=32)),
                ('event_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to='farmers_dashboard.cow')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
