# Generated by Django 6.0.3 on 2026-03-27 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_dashboard', '0004_reproductiveevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(max_length=64)),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_title', models.CharField(max_length=120)),
                ('provider_service_type', models.CharField(choices=[('veterinary', 'Veterinary'), ('artificial_insemination', 'Artificial insemination')], max_length=32)),
                ('provider_county', models.CharField(max_length=64)),
                ('provider_phone', models.CharField(blank=True, max_length=32)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read')], default='sent', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
