# Generated by Django 6.0.3 on 2026-03-21 06:50

from django.db import migrations, models


def seed_post_login_paths(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Role.objects.filter(slug="farmer").update(post_login_path="/")
    Role.objects.filter(slug="veterinary").update(post_login_path="/veterinary/")


def unseed_post_login_paths(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Role.objects.filter(slug__in=["farmer", "veterinary"]).update(post_login_path="")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_initial_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professional_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='post_login_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(seed_post_login_paths, unseed_post_login_paths),
    ]
