# Generated by Django 6.0.3 on 2026-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_professional_id_role_post_login_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farm_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_location_source',
            field=models.CharField(blank=True, choices=[('manual_pin', 'Pin on map'), ('current_location', 'Current location')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
